module(name = "keyshot")

bazel_dep(name = "rules_rust", version = "0.70.0")
bazel_dep(name = "gazelle", version = "0.47.0")
bazel_dep(name = "gazelle_rust", version = "0.1.0")
bazel_dep(name = "protobuf", version = "34.1")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.96.0"],
)
